README.md
=> installation instructions for macos sierra with python3

README.md
=> Dolarpy android version link added

coti.py
Corrige #7 
El websocket anterior ya no funciona (retorna connection refused)
=> Use new ALBERDI url

coti.py
=> Use new Interfisa endpoint

coti.py
Reverts melizeche/dolarPy#12
filter() implementation Not compatible with Python3
=> Revert "Use new Interfisa endpoint"

coti.py
De acuerdo a la información proveída por aVolpe en el Issue #11
Probado en Python 2.7 y 3.6.7
=> Corregida la cotización de Interfisa

coti.py
Modificamos el nombre de la clase a 'td.UICotizacion' porque no coincidia y agregamos replace de 'G. ' por ''.
=> Modicamos la funcion setgov(): nombre de clase y replace

coti.py, templates/index.html
Se agrega el servicio de MundialCambios SucAsunción
=> Se agrega el servicio de MundialCambios

coti.py
This PR fixes issue #28 
- Amambay (host moved to bancobasa.com.py when they rebranded, updated the URL)
- Mundial (New website, reworked the scrapper)
Cambios Alberdi's websocket is currently not working, so a fix isn't possible.
=> Fixed Broken rates

README.md, single_tweet_bot.py
=> Replaced Alberdi with Mundial exchange rate

coti.py, templates/index.html
=> Add La Moneda Cambios exchange rate

coti.py
=> Amambay provider webservice to scraping

README.md
=> APP android-kotlin

coti.py
Al parecer el ws dejó de funcionar, así que se optó por _scrapear_ directamente la página.
=> Update Alberdi scraper

coti.py, templates/index.html
Me tome el atrevimiento de corregir algunos enlaces que no estaban retonando valor.. 
Excelente proyecto..
=> Enlaces corregidos y amambay e interfisa comentados

coti.py
the url (https://www.bancognbcaminamosjuntos.com.py/Yaguarete/public/quotations) 
change for : new url -> https://www.bancognb.com.py/public/currency_quotations
On the web it is called:
=> Change Url GNB(ex BBVA) Quotation

coti.py
Ultimo pull para que se obtenga la cotización de GNB 😅
En GNB le agregaron un nombre a la lista de cotizaciones y al tratar de traer la cotización no encontraba
=> GNB service get from title list quotation from json

coti.py
Buenas Marce, se arreglo para obtener la cotización de alberdi de su [web](https://www.cambiosalberdi.com/langes/index.php#sectionCotizacion):
Prueba en terminal:
=> fix get quotation Cambios Alberdi

.gitignore, coti.py, requirements.txt, templates/index.html
This PR adds banco familiar to the app
=> Adds Banco Familiar

coti.py, templates/index.html
This PR removes the banco vision entry from the app.
=> remove banco vision
